Rancher token provider
billiford/arcade pull request #2
Opened 2021-03-25 20:16 UTC by dmrogers7

Adds Rancher as a token provider

The `provider` query parameter has been added to the `/tokens` endpoint and has two values
1. google
2. rancher
If no `provider` is supplied, then a google token is returned

2021-03-25 21:15 UTC, billiford requested changes
I think I messed up the module name when I originally set this up, as everything is referencing `github.homedepot.com/cd/...`. Should we consider moving this to the open-source homedepot org?

2021-03-25 21:15 UTC, billiford commented on pkg/http/token.go
> +func GetGoogleToken(c *gin.Context) {
We should make these unexported if possible.

```go
getGoogleToken(...)
getRancherToken(...)
```

2021-03-25 21:15 UTC, billiford commented on pkg/http/token.go
>  		if err != nil {
Let's format these lines to put the error next to the error check.
```go
		googleClient := google.Instance(c)
		
		token, err = googleClient.NewToken()
		if err != nil {
```

2021-03-25 21:15 UTC, billiford commented on README.md
> +export RANCHER_URL=https://rancher-np-ssc.homedepot.com/v3-public/activeDirectoryProviders/activedirectory?action=login
Let's do a more generic url...
```sh
export RANCHER_URL=https://rancher.example.com/v3-public/activeDirectoryProviders/activedirectory?action=login
```

2021-03-25 21:15 UTC, billiford commented on cmd/arcade/arcade.go
> +	"github.homedepot.com/cd/arcade/pkg/google"
I definitely started this issue... but why are we referencing `github.homedepot.com/cd/...`? Should we move this repo to the github org?

2021-03-25 21:15 UTC, billiford commented on pkg/http/token_test.go
> +	arcade_http "github.homedepot.com/cd/arcade/pkg/http"
I can't find the source on this right now, but I don't think we should be putting underscores on our imported packages. Instead maybe just say `arcadehttp`.

2021-03-25 21:15 UTC, billiford commented on pkg/rancher/payload_test.go
> +    "self": "https://rancher-np-ssc.homedepot.com/v3-public/tokens/kubeconfig-u-i76rfanbw5"
`https://rancher.example.com/v3-public/tokens/kubeconfig-u-i76rfanbw5`

2021-03-25 21:54 UTC, billiford commented
@dmrogers7 We can address the module issue outside of this PR unless you've already fixed it.

2021-03-25 21:56 UTC, billiford commented on pkg/http/token_test.go
> +	arcade_http "github.homedepot.com/cd/arcade/pkg/http"
Well I found the source that is referencing package names. I usually follow this convention for import names as well. https://blog.golang.org/package-names

2021-03-26 11:25 UTC, dmrogers7 commented on README.md
> +curl localhost:1982/tokens/provider=google -H "Api-Key: test"
doh!

2021-03-26 11:26 UTC, dmrogers7 commented
I made the fixes, including changing it to `gibhub.com/homedepot`.  Once this PR is merged, then we can fork the repo into the homedepot org

2021-03-26 13:43 UTC, billiford approved these changes
LGTM!

2021-03-26 13:43 UTC, merged